// SPDX-FileCopyrightText: Copyright 2025 Siemens AG
// SPDX-License-Identifier: BSD-3-Clause
// Code generated by go/internal/codegen. DO NOT EDIT.

package licenselynx

const (
	OrgSiemens Organization = "siemens"
)
