name: Data CI
on:
  push:
    branches:
      - main
    paths:
      - data/**
      - .github/workflows/data.yaml
  pull_request:
    branches:
      - main
    paths:
      - data/**
      - .github/workflows/data.yaml
jobs:
  validation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{secrets.PUSH_TOKEN}}
      - name: Install Poetry
        run: |
          pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: poetry
          cache-dependency-path: scripts/poetry.lock
      - name: Set Poetry environment
        run: |
          cd scripts
          poetry env use 3.11
      - name: Install dependencies
        run: |
          cd scripts
          poetry install --no-root
      - name: Run data validation
        run: |
          cd scripts
          poetry run data_validation
      - name: Run statistics file
        if: github.event.pull_request.base.ref == 'main'
        run: |
          python3 scripts/src/load/merge_data.py -o ./scripts/src/statistics/merged_data.json
          cd scripts/src/statistics
          python3 update_readme.py
          cd ../../../
      - name: Upload statistics file
        if: github.event.pull_request.base.ref == 'main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update statistics in README.md"
          branch: main
          commit_user_name: "CI/CD Push Token"
