name: Scripts CI
on:
  push:
    branches:
      - main
    paths:
      - scripts/**
      - .github/workflows/scripts.yaml
      - codecov.yml
  pull_request:
    branches:
      - main
    paths:
      - scripts/**
      - .github/workflows/scripts.yaml
      - codecov.yml
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Poetry
        run: |
          pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.11'
          cache: poetry
          cache-dependency-path: scripts/poetry.lock
      - name: Set Poetry environment
        run: |
          cd scripts
          poetry env use 3.11
      - name: Install dependencies
        run: |
          cd scripts
          poetry lock
          poetry install --no-root
      - name: Run the automated tests
        run: |
          cd scripts
          poetry run coverage run --branch -m pytest -vv
          poetry run coverage report --omit="tests/*"
          poetry run coverage xml --omit="tests/*"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: scripts/coverage.xml
          flags: scripts
          fail_ci_if_error: true
          disable_search: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}


  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Poetry
        run: |
          pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.11'
          cache: poetry
          cache-dependency-path: scripts/poetry.lock
      - name: Set Poetry environment
        run: |
          cd scripts
          poetry env use 3.11
      - name: Install dependencies
        run: |
          cd scripts
          poetry install --no-root
      - name: Run the linting
        run: |
          cd scripts
          poetry run mypy src tests
          poetry run flake8 src
          poetry run flake8 tests
